### PR TITLE
BIEBER

### PR DESCRIPTION
**Pull request by JMARCHESENYC**
@joshuabrainjaffe whats good homie!!!!

### CODE REVIEW

**Comment by mdwbkny** [comment]
@JMARCHESENYC This shit is so lame!

**Comment by joshuabrainjaffe** [comment]
I added the BEST SHITS.

**Comment by joshuabrainjaffe** [comment]
HAMPY McPAMPERS FA LYFE

**Comment by JMARCHESENYC** [comment]
smokey mad pot @mdwbkny @madhat5 @joshuabrainjaffe

**Comment by JMARCHESENYC** [comment]
ermmmmmergerrddddddd

**Pull request merged**
